### ISSUE TITLE
ControlImage example

### ISSUE THREAD

**Issue by rjacobs00** [UmSenhorQualquer/pyforms-gui#1]
I am unable to run the ControlsImage example in pyforms-gui-4\tutorials\Controls4Docs.
The GUI opens but once the open button is pressed the GUI crashes.
Here is the error that I receive: 

Traceback (most recent call last):
  File "ControlImage.py", line 31, in __open
    self._control.value = '/home/ricardo/Desktop/lena_color.png'
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyforms_gui\controls\control_image.py", line 73, in value
    self._imageWidget.paint([value])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyforms_gui\controls\control_player\AbstractGLWidget.py", line 328, in paint
    self.imgHeight, self.imgWidth = frames[0].shape[:2]
AttributeError: 'str' object has no attribute 'shape'

**Comment by jasonr18** [comment]
I had the same problem and found out that this problem is caused by the function `paint` need an array value. This array value represents the pictures and can produced by cv2.imread.
So the following change can fix the problem.( Also there is a change in the pic path)
`self._control.value = '/home/ricardo/Desktop/lena_color.png'`        ->
`self._control.value = cv2.imread('../2.ControlsExamples/lena.png')`

**Comment by MicBoucinha** [comment]
I made an additional change to your PR @CecilR 
```
file_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), '2.ControlsExamples', 'lena.png')
self._control.value = cv2.imread(file_path)
```
To make it work properly in different platforms. Thank you.
